version: 2

defaults: &defaults
  environment:
    NODE_ENV: development
  working_directory: ~/app
  docker:
    - image: circleci/node

jobs:
  build:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: yarn lint

      - persist_to_workspace:
          root: ~/app
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/app

      - run:
          name: Install NOW
          command: |
            echo 'export PATH=$(yarn global bin):$PATH' >> $BASH_ENV
            source $BASH_ENV
            yarn global add now

      - run:
          name: Build
          command: NODE_ENV=production yarn build

      - run:
          name: Deploy
          command: now -t $NOW_TOKEN

      - run:
          name: Create alias
          command: now -t $NOW_TOKEN alias

workflows:
  version: 2
  delivering:
    jobs:
      - build

      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - deploy
